ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ReactNativeSdkPaymentModuleExample' do
  config = use_native_modules!

  # Used to scan card
  pod 'LyraCardsRecognizer'

  dynamic_frameworks = ['LyraPaymentSDK', 'LyraMotion', 'LyraMaterial', 'SnapKit']

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

    pre_install do |installer|
    system("cd ../../ && npx bob build --target codegen")
    
    installer.pod_targets.each do |pod|
      if dynamic_frameworks.include?(pod.name)
        def pod.dynamic_framework?;
          true
        end
        def pod.build_type;
          Pod::BuildType.dynamic_framework
        end
      end
    end
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # TODO To remove once React Native have been updated
    # Workaround for pod fmt in Xcode 26.4 until RN updates fmt dependency to >= 12.1.0
    fmt_file = installer.sandbox.pod_dir('fmt').join('include/fmt/format-inl.h')
    if File.exist?(fmt_file)
      content = File.read(fmt_file)
      # Remplace tous les FMT_STRING("...") par juste "..."
      patched = content.gsub(/FMT_STRING\(("(?:[^"\\]|\\.)*")\)/, '\1')
      File.write(fmt_file, patched)
      puts "✅ fmt format-inl.h fully patched for Xcode 26.4 compatibility - TO REMOVE ASAP"
    else
      puts "⚠️  fmt format-inl.h not found, skipping patch"
    end
  end
end
